name: flauncher
description: Flutter-based Android TV launcher.

version: 2025.11.16+136

environment:
  sdk: ">=3.4.3"
  flutter: 3.38.1

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  image_picker: ^1.0.7
  intl: any
  http: ^1.1.0
  drift: ^2.14.1
  drift_local_storage_inspector: ^0.7.0
  path: ^1.9.0
  path_provider: ^2.0.13
  package_info_plus: ^7.0.0
  provider: ^6.0.5
  shared_preferences: ^2.3.3
  sqlite3_flutter_libs: ^0.5.13
  tuple: ^2.0.2
  flutter_localizations:
    sdk: flutter
  format: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^5.0.0
  mockito: ^5.3.2
  drift_dev: ^2.5.2
  network_image_mock: ^2.1.1
  transparent_image: ^2.0.1

  shared_preferences_platform_interface: any
  path_provider_platform_interface: any
  plugin_platform_interface: any
  package_info_plus_platform_interface: any
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
